
<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->
<div tabindex="0" aria-label="Map" id="mapcontainer" bind:this={webgl_canvas} />

<style>
  #mapcontainer {
    position: fixed;
    top: 142px;
    bottom: 0;
    width: 100%;
  }
  :global(.maplibregl-ctrl button) {
    margin: 0;
  }
</style>

<script>
  // imports
  import maplibregl from 'maplibre-gl';
  import {createEventDispatcher, onMount} from 'svelte';
  import {init_draw} from './drawing_utils.js';
  import {
    mapsource,
    maplayer,
    mapfunctions,
    mapobject,
    mapstyle,
    minzoom,
    maxzoom,
    maxbounds,

  } from './mapstore.js';

  const mapboxgl = maplibregl;
  let webgl_canvas;
  

  export let drawing_tools = false;

  /// MAP creation
  async function init() {;

    $mapobject = new mapboxgl.Map({
      container: 'mapcontainer',
      style: mapstyle,
      minZoom: minzoom,
      maxZoom: maxzoom,
      maxBounds: maxbounds,
      //   pitch: 10, // 30,
      center: [0, 53],
      zoom: 4,
      hash: false, // set options in hash string
    });

    document.querySelector('#mapcontainer div canvas').style.cursor = 'wait';

    // scale bar
    $mapobject.addControl(
      new mapboxgl.ScaleControl({
        position: 'bottom-left',
      })
    );

    // navigation
    $mapobject.addControl(new mapboxgl.NavigationControl(), 'bottom-right');

    //disable double click and rotation
    $mapobject.doubleClickZoom.disable();
    $mapobject.dragRotate.disable();

    // // correct error - ignore 403 missing tiles
    $mapobject.on('error', (e) => {
      if (
        e.error.status != 403 &&
        e.error.message != 'Failed to fetch' &&
        !/CORS/.test(e.error.message)
      ) {
        console.error('--', e.error.status, e.error.message);
        return e;
      }
    });

    $mapobject.on('load', SetLayers);
  }

  /// Set all Mapbox Parameters ///
  export async function SetLayers() {
    // set mapbox layers

    mapsource.subscribe(async () => {
      // set the sources
      for (const [key, value] of Object.entries($mapsource)) {
        if ($mapobject.getSource(key)) $mapobject.removeSource(key);
        if (!$mapobject.getSource(key)) $mapobject.addSource(key, value); // as it may nto be removable
      }
    });

    maplayer.subscribe(async () => {
      // set the layers
      for (const value of $maplayer) {
        if ($mapobject.getLayer(value.id)) $mapobject.removeLayer(value.id);
        $mapobject.addLayer(value);
      }
    });

    mapfunctions.subscribe(async () => {
      for (const e of $mapfunctions) {
        $mapobject.on(e.event, e.layer, e.callback);
      }
    });
    if (drawing_tools) await init_draw();
  }

  /// main
  onMount(init);
</script>

